services:
  laravel:
    image: doppler/laravel-app
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      - DOPPLER_TOKEN
    volumes:
      - laravel-public:/usr/src/app/public
    networks:
      - app
    ports:
      - '9000'
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      app:
        aliases:
          - db-local
          - db-staging
          - db-prod

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - laravel-public:/usr/src/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - app
    depends_on:
      - laravel

networks:
  app:

volumes:
  laravel-public:
